<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.326">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Maxime Labonne">
<meta name="dcterms.date" content="2022-03-05">
<meta name="description" content="Mixed Integer Programming for optimization with Google OR-Tools">

<title>Maxime Labonne - Integer vs.&nbsp;Linear Programming in Python</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/favicon.ico" rel="icon">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-4DWYJM47PC"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-4DWYJM47PC', { 'anonymize_ip': true});
</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Maxime Labonne - Integer vs.&nbsp;Linear Programming in Python">
<meta property="og:description" content="Mixed Integer Programming for optimization with Google OR-Tools">
<meta property="og:image" content="https://mlabonne.github.io/images/integerprogramming/thumbnail.jpg">
<meta property="og:site-name" content="Maxime Labonne">
<meta name="twitter:title" content="Maxime Labonne - Integer vs.&nbsp;Linear Programming in Python">
<meta name="twitter:description" content="Mixed Integer Programming for optimization with Google OR-Tools">
<meta name="twitter:image" content="https://mlabonne.github.io/images/integerprogramming/thumbnail.jpg">
<meta name="twitter:creator" content="@maximelabonne">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Maxime Labonne</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../publications.html" rel="" target="">
 <span class="menu-text">Publications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../book.html" rel="" target="">
 <span class="menu-text">Book</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mlabonne" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/maximelabonne" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Integer vs.&nbsp;Linear Programming in Python</h1>
                  <div>
        <div class="description">
          Mixed Integer Programming for optimization with Google OR-Tools
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">integer optimization</div>
                <div class="quarto-category">integer programming</div>
                <div class="quarto-category">OR-Tools</div>
                <div class="quarto-category">ortools</div>
                <div class="quarto-category">python</div>
                <div class="quarto-category">tutorial</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Maxime Labonne </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">March 5, 2022</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<center>
<img src="https://mlabonne.github.io/blog/images/integerprogramming/thumbnail.jpg">
</center>
<p>Why is <strong>linear programming</strong> called that way?</p>
<p>Both terms are confusing:</p>
<ul>
<li><strong>Linear</strong> implies that <strong>nonlinear</strong> programming exists;</li>
<li><strong>Programming</strong> actually means “<strong>planning</strong>” in this context.</li>
</ul>
<p>In summary, it has nothing to do with code: linear or not. It’s about <strong>optimizing</strong> variables with various constraints.</p>
<p>In this article, we’re gonna talk about another type of optimization: <strong>integer programming</strong>. We’ll see why a good understanding of the problem we face is necessary to choose the right solver. Finally, we will write a model that can take on a bigger challenge and actually solve a whole class of optimization problems.</p>
<p>You can run the code from this tutorial with the following <a href="https://colab.research.google.com/drive/1aIKnXPEiXFo1M3U0EM6arE2teD9KkJdF?usp=sharing"><strong>Google Colab notebook</strong></a>.</p>
<center>
<img src="https://mlabonne.github.io/blog/images/integerprogramming/units.png">
</center>
<section id="i.-optimization-problem-types" class="level2">
<h2 class="anchored" data-anchor-id="i.-optimization-problem-types">📊 I. Optimization problem&nbsp;types</h2>
<p>In the <a href="https://mlabonne.github.io/blog/linearoptimization/">introduction to linear programming</a>, we <strong>optimized an army composition</strong>. Here was the result:</p>
<div class="cell" data-outputid="9192b161-8737-430c-b548-12bb4bc18a0a">
<div class="cell-output cell-output-stdout">
<pre><code>================= Solution =================
Solved in 87.00 milliseconds in 2 iterations

Optimal power = 1800.0 💪power
Army:
 - 🗡️Swordsmen = 6.0000000000000036
 - 🏹Bowmen = 0.0
 - 🐎Horsemen = 5.999999999999999</code></pre>
</div>
</div>
<p>How can we have 5.999… horsemen? We specified that our variables <strong>should be integers</strong> with <code>VarInt</code>. What was wrong with our code?</p>
<p>The problem is not the model but the choice of the solver.</p>
<p>GLOP is a <a href="https://en.wikipedia.org/wiki/GLOP">pure linear programming solver</a>. This means that it cannot understand the concept of integers. It is limited to continuous parameters with a linear relationship.</p>
<p>This is the difference between <strong>linear</strong> programming (LP) and <strong>integer linear</strong> programming (ILP). In summary, LP solvers can only use real numbers and not integers as variables. So why did we declare our variables as integers if it doesn’t take them into account?</p>
<p>GLOP cannot solve ILP problems, but other solvers can. Actually, a lot of them are <strong>mixed integer linear programming</strong> (MILP, commonly called MIP) solvers. This means that they can consider both <strong>continuous</strong> (real numbers) and <strong>discrete</strong> (integers) variables. A particular case of discrete values is Boolean variables to represent decisions with 0–1 values.</p>
<p>Other solvers like SCIP or CBC can solve both <strong>MILP and MINLP</strong> (mixed integer <em>nonlinear</em> programming) problems. Thanks to OR-Tools, we can use the same model and just change the solver to SCIP or CBC.</p>
<div class="cell" data-outputid="a821a6bf-58ab-481e-b53e-3ccded71b1e2" data-execution_count="7">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the linear solver using the CBC backend</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>solver <span class="op">=</span> pywraplp.Solver(<span class="st">'Maximize army power'</span>, pywraplp.Solver.CBC_MIXED_INTEGER_PROGRAMMING)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Create the variables we want to optimize</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>swordsmen <span class="op">=</span> solver.IntVar(<span class="dv">0</span>, solver.infinity(), <span class="st">'swordsmen'</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>bowmen <span class="op">=</span> solver.IntVar(<span class="dv">0</span>, solver.infinity(), <span class="st">'bowmen'</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>horsemen <span class="op">=</span> solver.IntVar(<span class="dv">0</span>, solver.infinity(), <span class="st">'horsemen'</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Add constraints for each resource</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>solver.Add(swordsmen<span class="op">*</span><span class="dv">60</span> <span class="op">+</span> bowmen<span class="op">*</span><span class="dv">80</span> <span class="op">+</span> horsemen<span class="op">*</span><span class="dv">140</span> <span class="op">&lt;=</span> <span class="dv">1200</span>)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>solver.Add(swordsmen<span class="op">*</span><span class="dv">20</span> <span class="op">+</span> bowmen<span class="op">*</span><span class="dv">10</span> <span class="op">&lt;=</span> <span class="dv">800</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>solver.Add(bowmen<span class="op">*</span><span class="dv">40</span> <span class="op">+</span> horsemen<span class="op">*</span><span class="dv">100</span> <span class="op">&lt;=</span> <span class="dv">600</span>)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Maximize the objective function</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>solver.Maximize(swordsmen<span class="op">*</span><span class="dv">70</span> <span class="op">+</span> bowmen<span class="op">*</span><span class="dv">95</span> <span class="op">+</span> horsemen<span class="op">*</span><span class="dv">230</span>)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Solve problem</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>status <span class="op">=</span> solver.Solve()</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="co"># If an optimal solution has been found, print results</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> status <span class="op">==</span> pywraplp.Solver.OPTIMAL:</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(<span class="st">'================= Solution ================='</span>)</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(<span class="ss">f'Solved in </span><span class="sc">{</span>solver<span class="sc">.</span>wall_time()<span class="sc">:.2f}</span><span class="ss"> milliseconds in </span><span class="sc">{</span>solver<span class="sc">.</span>iterations()<span class="sc">}</span><span class="ss"> iterations'</span>)</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>()</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(<span class="ss">f'Optimal value = </span><span class="sc">{</span>solver<span class="sc">.</span>Objective()<span class="sc">.</span>Value()<span class="sc">}</span><span class="ss"> 💪power'</span>)</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(<span class="st">'Army:'</span>)</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(<span class="ss">f' - 🗡️Swordsmen = </span><span class="sc">{</span>swordsmen<span class="sc">.</span>solution_value()<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(<span class="ss">f' - 🏹Bowmen = </span><span class="sc">{</span>bowmen<span class="sc">.</span>solution_value()<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(<span class="ss">f' - 🐎Horsemen = </span><span class="sc">{</span>horsemen<span class="sc">.</span>solution_value()<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(<span class="st">'The solver could not find an optimal solution.'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>================= Solution =================
Solved in 3.00 milliseconds in 0 iterations

Optimal value = 1800.0 💪power
Army:
 - 🗡️Swordsmen = 6.0
 - 🏹Bowmen = 0.0
 - 🐎Horsemen = 6.0</code></pre>
</div>
</div>
<p>Strictly speaking, our variables are still floats (<code>type(swordsmen.solution_value()) = float</code>) but we can see that they don’t have weird decimals anymore: the CBC solver really considered them as <strong>integers</strong>.</p>
<p>In this example, we would generally just <strong>round up these values</strong> since the error is insignificant. However, it is important to remember to choose the appropriate solver according to the studied problem:</p>
<ul>
<li><strong>LP</strong> for continuous variables;</li>
<li><strong>MIP/MILP</strong> for a combination of continuous and discrete variables.</li>
</ul>
<p>There are other types such as <strong>quadratic</strong> (QP) or <strong>nonlinear</strong> (NLP or MINLP, with an exponential objective function or constraints for instance) problems. They’re applied in different contexts, but follow the same principles as LP or MIP solvers.</p>
<center>
<img src="https://mlabonne.github.io/blog/images/integerprogramming/continuousvsdiscrete.png">
</center>
</section>
<section id="ii.-building-a-general-model" class="level2">
<h2 class="anchored" data-anchor-id="ii.-building-a-general-model">🧱 II. Building a general model</h2>
<p>But what if our <strong>resources change</strong>? Or if the cost of a unit evolved? What if we upgraded horsemen and their power increased?</p>
<p>One of the best perks of OR-Tools is that it uses a general-purpose programming language like Python. Instead of static numbers, we can store our parameters in objects like <strong>dictionaries</strong> or <strong>lists</strong>.</p>
<p>The code won’t be as readable, but it becomes much more flexible: actually, it can be so flexible that we can solve an <strong>entire class of optimization problems</strong> without changing the model (just the parameters).</p>
<p>Let’s transform our input parameters into Python lists and feed them to the solver through a function.</p>
<div class="cell" data-outputid="700e65e6-1e9b-4f1f-f4e3-6d7ba728340d" data-execution_count="8">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Inputs</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>UNITS <span class="op">=</span> [<span class="st">'🗡️Swordsmen'</span>, <span class="st">'🏹Bowmen'</span>, <span class="st">'🐎Horsemen'</span>]</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>DATA <span class="op">=</span> [[<span class="dv">60</span>, <span class="dv">20</span>, <span class="dv">0</span>, <span class="dv">70</span>],</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>        [<span class="dv">80</span>, <span class="dv">10</span>, <span class="dv">40</span>, <span class="dv">95</span>],</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>        [<span class="dv">140</span>, <span class="dv">0</span>, <span class="dv">100</span>, <span class="dv">230</span>]]</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>RESOURCES <span class="op">=</span> [<span class="dv">1200</span>, <span class="dv">800</span>, <span class="dv">600</span>]</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> solve_army(UNITS, DATA, RESOURCES):</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create the linear solver using the CBC backend</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>  solver <span class="op">=</span> pywraplp.Solver(<span class="st">'Maximize army power'</span>, pywraplp.Solver.CBC_MIXED_INTEGER_PROGRAMMING)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 1. Create the variables we want to optimize</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>  units <span class="op">=</span> [solver.IntVar(<span class="dv">0</span>, solver.infinity(), unit) <span class="cf">for</span> unit <span class="kw">in</span> UNITS]</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2. Add constraints for each resource</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> r, _ <span class="kw">in</span> <span class="bu">enumerate</span>(RESOURCES):</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    solver.Add(<span class="bu">sum</span>(DATA[u][r] <span class="op">*</span> units[u] <span class="cf">for</span> u, _ <span class="kw">in</span> <span class="bu">enumerate</span>(units)) <span class="op">&lt;=</span> RESOURCES[r])</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 3. Maximize the objective function</span></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>  solver.Maximize(<span class="bu">sum</span>(DATA[u][<span class="op">-</span><span class="dv">1</span>] <span class="op">*</span> units[u] <span class="cf">for</span> u, _ <span class="kw">in</span> <span class="bu">enumerate</span>(units)))</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Solve problem</span></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>  status <span class="op">=</span> solver.Solve()</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>  <span class="co"># If an optimal solution has been found, print results</span></span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> status <span class="op">==</span> pywraplp.Solver.OPTIMAL:</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'================= Solution ================='</span>)</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'Solved in </span><span class="sc">{</span>solver<span class="sc">.</span>wall_time()<span class="sc">:.2f}</span><span class="ss"> milliseconds in </span><span class="sc">{</span>solver<span class="sc">.</span>iterations()<span class="sc">}</span><span class="ss"> iterations'</span>)</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>()</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'Optimal value = </span><span class="sc">{</span>solver<span class="sc">.</span>Objective()<span class="sc">.</span>Value()<span class="sc">}</span><span class="ss"> 💪power'</span>)</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'Army:'</span>)</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> u, _ <span class="kw">in</span> <span class="bu">enumerate</span>(units):</span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>      <span class="bu">print</span>(<span class="ss">f' - </span><span class="sc">{</span>units[u]<span class="sc">.</span>name()<span class="sc">}</span><span class="ss"> = </span><span class="sc">{</span>units[u]<span class="sc">.</span>solution_value()<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>  <span class="cf">else</span>:</span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'The solver could not find an optimal solution.'</span>)</span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>solve_army(UNITS, DATA, RESOURCES)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>================= Solution =================
Solved in 2.00 milliseconds in 0 iterations

Optimal value = 1800.0 💪power
Army:
 - 🗡️Swordsmen = 6.0
 - 🏹Bowmen = 0.0
 - 🐎Horsemen = 6.0</code></pre>
</div>
</div>
<p>We obtain the same results: our code seems to work. Now let’s <strong>change the parameters</strong> to tackle a slightly more complex problem.</p>
<p>Imagine we have a lot more resources: 🌾<strong>183000</strong>, 🪵<strong>90512</strong>, and 🪙<strong>80150</strong>, so we can also produce a lot more units! This is the new table:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Unit</th>
<th style="text-align: center;">🌾Food</th>
<th style="text-align: center;">🪵Wood</th>
<th style="text-align: center;">🪙Gold</th>
<th style="text-align: center;">💪Attack</th>
<th style="text-align: center;">❤️Health</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">🗡️Swordsman</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">70</td>
</tr>
<tr class="even">
<td style="text-align: left;">🛡️Man-at-arms</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">155</td>
</tr>
<tr class="odd">
<td style="text-align: left;">🏹Bowman</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">70</td>
</tr>
<tr class="even">
<td style="text-align: left;">❌Crossbowman</td>
<td style="text-align: center;">80</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">80</td>
</tr>
<tr class="odd">
<td style="text-align: left;">🔫Handcannoneer</td>
<td style="text-align: center;">120</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">120</td>
<td style="text-align: center;">35</td>
<td style="text-align: center;">150</td>
</tr>
<tr class="even">
<td style="text-align: left;">🐎Horseman</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">125</td>
</tr>
<tr class="odd">
<td style="text-align: left;">♞Knight</td>
<td style="text-align: center;">140</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">24</td>
<td style="text-align: center;">230</td>
</tr>
<tr class="even">
<td style="text-align: left;">🐏Battering ram</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">300</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">200</td>
<td style="text-align: center;">700</td>
</tr>
<tr class="odd">
<td style="text-align: left;">🎯Springald</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">250</td>
<td style="text-align: center;">250</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">200</td>
</tr>
</tbody>
</table>
<p>Notice that we transformed the 💪<strong>power</strong> into two values: 💪<strong>attack</strong> and ❤️<strong>health</strong>, which is a little more detailed. Health values are higher than attack values, which is why we want to add a weighting factor to make them more comparable.</p>
<p>Let’s take 10 as an example, so <span class="math inline">\(power = 10 \times attack + health\)</span>. Our objective function becomes:</p>
<p><span class="math display">\[maximize \ \sum_{u \in units} (10\times attack + health) \cdot u\]</span></p>
<p>Adapting our code to this new problem is actually quite simple: we just have to <strong>change the input parameters</strong> and update the <strong>objective function</strong>.</p>
<div class="cell" data-outputid="e85623bc-00c0-4a62-e463-253fc6ce7a5c" data-execution_count="9">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>UNITS <span class="op">=</span> [</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'🗡️Swordsmen'</span>,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'🛡️Men-at-arms'</span>,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'🏹Bowmen'</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'❌Crossbowmen'</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'🔫Handcannoneers'</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'🐎Horsemen'</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'♞Knights'</span>,</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'🐏Battering rams'</span>,</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'🎯Springalds'</span>,</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'🪨Mangonels'</span>,</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>DATA <span class="op">=</span> [</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">60</span>, <span class="dv">20</span>, <span class="dv">0</span>, <span class="dv">6</span>, <span class="dv">70</span>],</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">100</span>, <span class="dv">0</span>, <span class="dv">20</span>, <span class="dv">12</span>, <span class="dv">155</span>],</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">30</span>, <span class="dv">50</span>, <span class="dv">0</span>, <span class="dv">5</span>, <span class="dv">70</span>],</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">80</span>, <span class="dv">0</span>, <span class="dv">40</span>, <span class="dv">12</span>, <span class="dv">80</span>],</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">120</span>, <span class="dv">0</span>, <span class="dv">120</span>, <span class="dv">35</span>, <span class="dv">150</span>],</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">100</span>, <span class="dv">20</span>, <span class="dv">0</span>, <span class="dv">9</span>, <span class="dv">125</span>],</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">140</span>, <span class="dv">0</span>, <span class="dv">100</span>, <span class="dv">24</span>, <span class="dv">230</span>],</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">0</span>, <span class="dv">300</span>, <span class="dv">0</span>, <span class="dv">200</span>, <span class="dv">700</span>],</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">0</span>, <span class="dv">250</span>, <span class="dv">250</span>, <span class="dv">30</span>, <span class="dv">200</span>],</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">0</span>, <span class="dv">400</span>, <span class="dv">200</span>, <span class="dv">12</span><span class="op">*</span><span class="dv">3</span>, <span class="dv">240</span>]</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>RESOURCES <span class="op">=</span> [<span class="dv">183000</span>, <span class="dv">90512</span>, <span class="dv">80150</span>]</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> solve_army(UNITS, DATA, RESOURCES):</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create the linear solver using the CBC backend</span></span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>  solver <span class="op">=</span> pywraplp.Solver(<span class="st">'Maximize army power'</span>, pywraplp.Solver.CBC_MIXED_INTEGER_PROGRAMMING)</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 1. Create the variables we want to optimize</span></span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>  units <span class="op">=</span> [solver.IntVar(<span class="dv">0</span>, solver.infinity(), unit) <span class="cf">for</span> unit <span class="kw">in</span> UNITS]</span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2. Add constraints for each resource</span></span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> r, _ <span class="kw">in</span> <span class="bu">enumerate</span>(RESOURCES):</span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a>    solver.Add(<span class="bu">sum</span>(DATA[u][r] <span class="op">*</span> units[u] <span class="cf">for</span> u, _ <span class="kw">in</span> <span class="bu">enumerate</span>(units)) <span class="op">&lt;=</span> RESOURCES[r])</span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 3. Maximize the new objective function</span></span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a>  solver.Maximize(<span class="bu">sum</span>((<span class="dv">10</span><span class="op">*</span>DATA[u][<span class="op">-</span><span class="dv">2</span>] <span class="op">+</span> DATA[u][<span class="op">-</span><span class="dv">1</span>]) <span class="op">*</span> units[u] <span class="cf">for</span> u, _ <span class="kw">in</span> <span class="bu">enumerate</span>(units)))</span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Solve problem</span></span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a>  status <span class="op">=</span> solver.Solve()</span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a>  <span class="co"># If an optimal solution has been found, print results</span></span>
<span id="cb6-48"><a href="#cb6-48" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> status <span class="op">==</span> pywraplp.Solver.OPTIMAL:</span>
<span id="cb6-49"><a href="#cb6-49" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'================= Solution ================='</span>)</span>
<span id="cb6-50"><a href="#cb6-50" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'Solved in </span><span class="sc">{</span>solver<span class="sc">.</span>wall_time()<span class="sc">:.2f}</span><span class="ss"> milliseconds in </span><span class="sc">{</span>solver<span class="sc">.</span>iterations()<span class="sc">}</span><span class="ss"> iterations'</span>)</span>
<span id="cb6-51"><a href="#cb6-51" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>()</span>
<span id="cb6-52"><a href="#cb6-52" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'Optimal value = </span><span class="sc">{</span>solver<span class="sc">.</span>Objective()<span class="sc">.</span>Value()<span class="sc">}</span><span class="ss"> 💪power'</span>)</span>
<span id="cb6-53"><a href="#cb6-53" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'Army:'</span>)</span>
<span id="cb6-54"><a href="#cb6-54" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> u, _ <span class="kw">in</span> <span class="bu">enumerate</span>(units):</span>
<span id="cb6-55"><a href="#cb6-55" aria-hidden="true" tabindex="-1"></a>      <span class="bu">print</span>(<span class="ss">f' - </span><span class="sc">{</span>units[u]<span class="sc">.</span>name()<span class="sc">}</span><span class="ss"> = </span><span class="sc">{</span>units[u]<span class="sc">.</span>solution_value()<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb6-56"><a href="#cb6-56" aria-hidden="true" tabindex="-1"></a>  <span class="cf">else</span>:</span>
<span id="cb6-57"><a href="#cb6-57" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'The solver could not find an optimal solution.'</span>)</span>
<span id="cb6-58"><a href="#cb6-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-59"><a href="#cb6-59" aria-hidden="true" tabindex="-1"></a>solve_army(UNITS, DATA, RESOURCES)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>================= Solution =================
Solved in 74.00 milliseconds in 412 iterations

Optimal value = 1393145.0 💪power
Army:
 - 🗡️Swordsmen = 2.0
 - 🛡️Men-at-arms = 1283.0
 - 🏹Bowmen = 3.0
 - ❌Crossbowmen = 0.0
 - 🔫Handcannoneers = 454.0
 - 🐎Horsemen = 0.0
 - ♞Knights = 0.0
 - 🐏Battering rams = 301.0
 - 🎯Springalds = 0.0
 - 🪨Mangonels = 0.0</code></pre>
</div>
</div>
<p>This problem would take a long time for humans to address, but the ILP solver did it in the blink of an eye. Better than that: it also gives us the guarantee that <strong>our solution is optimal</strong>, which means that our enemy cannot find a better army composition for the same cost!</p>
<p>We could increase the number of units and give billions of resources but you get the picture: it would just take longer to obtain a solution, but it wouldn’t change the problem.</p>
</section>
<section id="iii.-combining-constraints" class="level2">
<h2 class="anchored" data-anchor-id="iii.-combining-constraints">⚔️ III. Combining constraints</h2>
<p>Now, let’s say we scouted our enemy and know that their army has a 💪power of <strong>1,000,000</strong>. We could build a much better army, but our resources are precious and it wouldn’t be very efficient: all we have to do is to build an army with a 💪<strong>power higher than 1,000,000</strong> (even 1,000,001 would be enough).</p>
<p>In other words, the total power is now a <strong>constraint</strong> (💪 &gt; 1,000,000) instead of the objective to maximize. The new goal is to minimize the resources we need to produce this army. However, we can reuse our input parameters since they didn’t change.</p>
<p>The new constraint can be translated as “the sum of the power of the selected units must be strictly greater than 1,000,000”.</p>
<p><span class="math display">\[\sum_{u \in units} (10\times attack + health) \cdot u &gt; 1\,000\,000\]</span></p>
<p>In code, we can loop through our units and resources to design this constraint.</p>
<p>The objective function also has to change. Our goal is to <strong>minimize the sum of resources spent</strong> to build the army.</p>
<p><span class="math display">\[minimize \ \sum_{u \in units} (food + wood + gold) \cdot u\]</span></p>
<p>Once again, we can loop through our resources to implement it in OR-Tools.</p>
<div class="cell" data-outputid="c2bb06c0-4214-4fa8-c85a-a3191c17612a" data-execution_count="10">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> solve_army(UNITS, DATA, RESOURCES):</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create the linear solver using the CBC backend</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  solver <span class="op">=</span> pywraplp.Solver(<span class="st">'Minimize resource consumption'</span>, pywraplp.Solver.CBC_MIXED_INTEGER_PROGRAMMING)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 1. Create the variables we want to optimize</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  units <span class="op">=</span> [solver.IntVar(<span class="dv">0</span>, solver.infinity(), unit) <span class="cf">for</span> unit <span class="kw">in</span> UNITS]</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2. Add power constraint</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  solver.Add(<span class="bu">sum</span>((<span class="dv">10</span> <span class="op">*</span> DATA[u][<span class="op">-</span><span class="dv">2</span>] <span class="op">+</span> DATA[u][<span class="op">-</span><span class="dv">1</span>]) <span class="op">*</span> units[u] <span class="cf">for</span> u, _ <span class="kw">in</span> <span class="bu">enumerate</span>(units)) <span class="op">&gt;=</span> <span class="dv">1000001</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 3. Minimize the objective function</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  solver.Minimize(<span class="bu">sum</span>((DATA[u][<span class="dv">0</span>] <span class="op">+</span> DATA[u][<span class="dv">1</span>] <span class="op">+</span> DATA[u][<span class="dv">2</span>]) <span class="op">*</span> units[u] <span class="cf">for</span> u, _ <span class="kw">in</span> <span class="bu">enumerate</span>(units)))</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Solve problem</span></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>  status <span class="op">=</span> solver.Solve()</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># If an optimal solution has been found, print results</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> status <span class="op">==</span> pywraplp.Solver.OPTIMAL:</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'================= Solution ================='</span>)</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'Solved in </span><span class="sc">{</span>solver<span class="sc">.</span>wall_time()<span class="sc">:.2f}</span><span class="ss"> milliseconds in </span><span class="sc">{</span>solver<span class="sc">.</span>iterations()<span class="sc">}</span><span class="ss"> iterations'</span>)</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>()</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>    power <span class="op">=</span> <span class="bu">sum</span>((<span class="dv">10</span> <span class="op">*</span> DATA[u][<span class="op">-</span><span class="dv">2</span>] <span class="op">+</span> DATA[u][<span class="op">-</span><span class="dv">1</span>]) <span class="op">*</span> units[u].solution_value() <span class="cf">for</span> u, _ <span class="kw">in</span> <span class="bu">enumerate</span>(units))</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'Optimal value = </span><span class="sc">{</span>solver<span class="sc">.</span>Objective()<span class="sc">.</span>Value()<span class="sc">}</span><span class="ss"> 🌾🪵🪙resources'</span>)</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'Power = 💪</span><span class="sc">{</span>power<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'Army:'</span>)</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> u, _ <span class="kw">in</span> <span class="bu">enumerate</span>(units):</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>      <span class="bu">print</span>(<span class="ss">f' - </span><span class="sc">{</span>units[u]<span class="sc">.</span>name()<span class="sc">}</span><span class="ss"> = </span><span class="sc">{</span>units[u]<span class="sc">.</span>solution_value()<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>()</span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a>    food <span class="op">=</span> <span class="bu">sum</span>((DATA[u][<span class="dv">0</span>]) <span class="op">*</span> units[u].solution_value() <span class="cf">for</span> u, _ <span class="kw">in</span> <span class="bu">enumerate</span>(units))</span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a>    wood <span class="op">=</span> <span class="bu">sum</span>((DATA[u][<span class="dv">1</span>]) <span class="op">*</span> units[u].solution_value() <span class="cf">for</span> u, _ <span class="kw">in</span> <span class="bu">enumerate</span>(units))</span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a>    gold <span class="op">=</span> <span class="bu">sum</span>((DATA[u][<span class="dv">2</span>]) <span class="op">*</span> units[u].solution_value() <span class="cf">for</span> u, _ <span class="kw">in</span> <span class="bu">enumerate</span>(units))</span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'Resources:'</span>)</span>
<span id="cb8-35"><a href="#cb8-35" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f' - 🌾Food = </span><span class="sc">{</span>food<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb8-36"><a href="#cb8-36" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f' - 🪵Wood = </span><span class="sc">{</span>wood<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb8-37"><a href="#cb8-37" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f' - 🪙Gold = </span><span class="sc">{</span>gold<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb8-38"><a href="#cb8-38" aria-hidden="true" tabindex="-1"></a>  <span class="cf">else</span>:</span>
<span id="cb8-39"><a href="#cb8-39" aria-hidden="true" tabindex="-1"></a>      <span class="bu">print</span>(<span class="st">'The solver could not find an optimal solution.'</span>)</span>
<span id="cb8-40"><a href="#cb8-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-41"><a href="#cb8-41" aria-hidden="true" tabindex="-1"></a>solve_army(UNITS, DATA, RESOURCES)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>================= Solution =================
Solved in 4.00 milliseconds in 0 iterations

Optimal value = 111300.0 🌾🪵🪙resources
Power = 💪1001700.0
Army:
 - 🗡️Swordsmen = 0.0
 - 🛡️Men-at-arms = 0.0
 - 🏹Bowmen = 0.0
 - ❌Crossbowmen = 0.0
 - 🔫Handcannoneers = 0.0
 - 🐎Horsemen = 0.0
 - ♞Knights = 0.0
 - 🐏Battering rams = 371.0
 - 🎯Springalds = 0.0
 - 🪨Mangonels = 0.0

Resources:
 - 🌾Food = 0.0
 - 🪵Wood = 111300.0
 - 🪙Gold = 0.0</code></pre>
</div>
</div>
<p>The solver found an optimal solution: we need to build <strong>371 🐏battering rams</strong> for a total cost of 111,300 🪵wood. Wait, what if we don’t have that much wood? In the previous section, we only had 🪵90512: we cannot produce 371 🐏battering rams. 😱</p>
<p>So is it possible to take these <strong>limited resources</strong> into account and still try to <strong>build the best army</strong>? Actually, it’s super easy: we just have to copy/paste the constraints from the previous section.</p>
<p>In this version, we have two types of constraints:</p>
<ul>
<li>The total power must be <strong>greater than 1,000,000</strong>;</li>
<li>We cannot spend more than our <strong>limited resources</strong>.</li>
</ul>
<div class="cell" data-outputid="aa8815a5-fb1e-452e-8aa9-4988c98b1494" data-execution_count="11">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> solve_army(UNITS, DATA, RESOURCES):</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create the linear solver using the CBC backend</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  solver <span class="op">=</span> pywraplp.Solver(<span class="st">'Minimize resource consumption'</span>, pywraplp.Solver.CBC_MIXED_INTEGER_PROGRAMMING)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 1. Create the variables we want to optimize</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  units <span class="op">=</span> [solver.IntVar(<span class="dv">0</span>, solver.infinity(), unit) <span class="cf">for</span> unit <span class="kw">in</span> UNITS]</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2. Add constraints for each resource</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> r, _ <span class="kw">in</span> <span class="bu">enumerate</span>(RESOURCES):</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    solver.Add(<span class="bu">sum</span>((<span class="dv">10</span> <span class="op">*</span> DATA[u][<span class="op">-</span><span class="dv">2</span>] <span class="op">+</span> DATA[u][<span class="op">-</span><span class="dv">1</span>]) <span class="op">*</span> units[u] <span class="cf">for</span> u, _ <span class="kw">in</span> <span class="bu">enumerate</span>(units)) <span class="op">&gt;=</span> <span class="dv">1000001</span>)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Old constraints for limited resources</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> r, _ <span class="kw">in</span> <span class="bu">enumerate</span>(RESOURCES):</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>    solver.Add(<span class="bu">sum</span>(DATA[u][r] <span class="op">*</span> units[u] <span class="cf">for</span> u, _ <span class="kw">in</span> <span class="bu">enumerate</span>(units)) <span class="op">&lt;=</span> RESOURCES[r])</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 3. Minimize the objective function</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>  solver.Minimize(<span class="bu">sum</span>((DATA[u][<span class="dv">0</span>] <span class="op">+</span> DATA[u][<span class="dv">1</span>] <span class="op">+</span> DATA[u][<span class="dv">2</span>]) <span class="op">*</span> units[u] <span class="cf">for</span> u, _ <span class="kw">in</span> <span class="bu">enumerate</span>(units)))</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Solve problem</span></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>  status <span class="op">=</span> solver.Solve()</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>  <span class="co"># If an optimal solution has been found, print results</span></span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> status <span class="op">==</span> pywraplp.Solver.OPTIMAL:</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'================= Solution ================='</span>)</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'Solved in </span><span class="sc">{</span>solver<span class="sc">.</span>wall_time()<span class="sc">:.2f}</span><span class="ss"> milliseconds in </span><span class="sc">{</span>solver<span class="sc">.</span>iterations()<span class="sc">}</span><span class="ss"> iterations'</span>)</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>()</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>    power <span class="op">=</span> <span class="bu">sum</span>((<span class="dv">10</span> <span class="op">*</span> DATA[u][<span class="op">-</span><span class="dv">2</span>] <span class="op">+</span> DATA[u][<span class="op">-</span><span class="dv">1</span>]) <span class="op">*</span> units[u].solution_value() <span class="cf">for</span> u, _ <span class="kw">in</span> <span class="bu">enumerate</span>(units))</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'Optimal value = </span><span class="sc">{</span>solver<span class="sc">.</span>Objective()<span class="sc">.</span>Value()<span class="sc">}</span><span class="ss"> 🌾🪵🪙resources'</span>)</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'Power = 💪</span><span class="sc">{</span>power<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'Army:'</span>)</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> u, _ <span class="kw">in</span> <span class="bu">enumerate</span>(units):</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>      <span class="bu">print</span>(<span class="ss">f' - </span><span class="sc">{</span>units[u]<span class="sc">.</span>name()<span class="sc">}</span><span class="ss"> = </span><span class="sc">{</span>units[u]<span class="sc">.</span>solution_value()<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>()</span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a>    food <span class="op">=</span> <span class="bu">sum</span>((DATA[u][<span class="dv">0</span>]) <span class="op">*</span> units[u].solution_value() <span class="cf">for</span> u, _ <span class="kw">in</span> <span class="bu">enumerate</span>(units))</span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a>    wood <span class="op">=</span> <span class="bu">sum</span>((DATA[u][<span class="dv">1</span>]) <span class="op">*</span> units[u].solution_value() <span class="cf">for</span> u, _ <span class="kw">in</span> <span class="bu">enumerate</span>(units))</span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a>    gold <span class="op">=</span> <span class="bu">sum</span>((DATA[u][<span class="dv">2</span>]) <span class="op">*</span> units[u].solution_value() <span class="cf">for</span> u, _ <span class="kw">in</span> <span class="bu">enumerate</span>(units))</span>
<span id="cb10-39"><a href="#cb10-39" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'Resources:'</span>)</span>
<span id="cb10-40"><a href="#cb10-40" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f' - 🌾Food = </span><span class="sc">{</span>food<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb10-41"><a href="#cb10-41" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f' - 🪵Wood = </span><span class="sc">{</span>wood<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb10-42"><a href="#cb10-42" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f' - 🪙Gold = </span><span class="sc">{</span>gold<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb10-43"><a href="#cb10-43" aria-hidden="true" tabindex="-1"></a>  <span class="cf">else</span>:</span>
<span id="cb10-44"><a href="#cb10-44" aria-hidden="true" tabindex="-1"></a>      <span class="bu">print</span>(<span class="st">'The solver could not find an optimal solution.'</span>)</span>
<span id="cb10-45"><a href="#cb10-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-46"><a href="#cb10-46" aria-hidden="true" tabindex="-1"></a>solve_army(UNITS, DATA, RESOURCES)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>================= Solution =================
Solved in 28.00 milliseconds in 1 iterations

Optimal value = 172100.0 🌾🪵🪙resources
Power = 💪1000105.0
Army:
 - 🗡️Swordsmen = 1.0
 - 🛡️Men-at-arms = 681.0
 - 🏹Bowmen = 0.0
 - ❌Crossbowmen = 0.0
 - 🔫Handcannoneers = 0.0
 - 🐎Horsemen = 0.0
 - ♞Knights = 0.0
 - 🐏Battering rams = 301.0
 - 🎯Springalds = 0.0
 - 🪨Mangonels = 0.0

Resources:
 - 🌾Food = 68160.0
 - 🪵Wood = 90320.0
 - 🪙Gold = 13620.0</code></pre>
</div>
</div>
<p>Since we now have a <strong>limited resource of 🪵wood</strong>, the number of 🐏battering rams sadly dropped from 371 to 301. In exchange, we got 681 🛡️men-at-arms and 1 lost 🗡️swordsman (welcome to them).</p>
<p>The total cost of the army is <strong>172,100</strong>, which is much higher than the 111,300 we previously found (+65% increase) but it truly is the optimal solution under these constraints. It shows that we should produce more wood because these 🐏 battering rams are extremely cost-efficient!</p>
<p>This example shows <strong>how modular</strong> LP models can be. It is possible to reuse parts of the code, like constraints, in another model to combine them and solve more complex problems.</p>
</section>
<section id="iv.-linear-programming-vs-machine-learning" class="level2">
<h2 class="anchored" data-anchor-id="iv.-linear-programming-vs-machine-learning">🧠 IV. Linear Programming vs Machine&nbsp;Learning</h2>
<p>Let’s talk about the elephant in the room. Why not use <strong>machine learning</strong> (in a broad sense) instead of linear programming? It’s not like this problem cannot be solved with a genetic algorithm for instance.</p>
<p>Mathematical optimization is often neglected in favor of machine learning techniques, but both have their merits:</p>
<ul>
<li>Linear programming can produce an <strong>optimal solution</strong> in an undetermined amount of time (it can take years), while machine learning can approximate complex functions in no time.</li>
<li>There is <strong>no training</strong> in LP, but an expert is required to build a mathematical model. Machine learning needs data, but the models can be used as black boxes to solve a problem.</li>
<li>As a rule of thumb, problems that <strong>do not have a particular time constraint</strong> and/or are not extremely complex can be advantageously solved with linear programming.</li>
</ul>
<center>
<img src="https://mlabonne.github.io/blog/images/integerprogramming/lpvsml.png">
</center>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>In this tutorial, we dived deeper into our understanding of mathematical optimization.</p>
<ul>
<li>We talked about solvers and types of optimization problems: <strong>LP, MIP, NLP</strong>;</li>
<li>We modeled and solved an extremely common optimization problem in an optimal way and <strong>generalized our model</strong> through a function;</li>
<li>We reframed this problem and <strong>merged two sets of constraints</strong> to obtain the best army composition for the lowest price;</li>
<li>We compared the <strong>pros and cons</strong> of linear programming and machine learning.</li>
</ul>
<p>There are <strong>a lot more problems</strong> where optimization can be applied. For instance, how to create school timetables that satisfy everybody’s requirements? How to deliver 1,000 different orders in a minimum amount of time? Where to create a new metro line to maximize its usefulness?</p>
<p>In future articles, we’ll talk about new types of applications for these techniques, including satisfiability and nonlinear problems.</p>
<p>I hope you enjoyed this more advanced article. If you like machine learning and optimization, <a href="https://twitter.com/maximelabonne"><strong>let’s connect on Twitter</strong></a>!</p>
</section>
<section id="linear-programming-course" class="level2">
<h2 class="anchored" data-anchor-id="linear-programming-course">🥇 Linear Programming Course</h2>
<p><a href="https://github.com/mlabonne/Linear-Programming-Course" class="related">🔎 Course overview</a></p>
<p><a href="https://mlabonne.github.io/blog/linearoptimization/" class="related">📝 Chapter 1: Introduction to Linear Programming</a></p>
<p><a href="https://mlabonne.github.io/blog/integerprogramming/" class="related">📝 Chapter 2: Integer vs.&nbsp;Linear Programming</a></p>
<p><a href="https://mlabonne.github.io/blog/constraintprogramming/" class="related">📝 Chapter 3: Constraint Programming</a></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>